### ISSUE TITLE
Towards 0.2.1

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#13]
### Done 

* [x] schema show tests and decision (issue #6 and PR #10)
* [x] docs (issue #7, PR #15 )
* [x] automatic type suggestion `autotype` (#4)
