### ISSUE TITLE
Towards 0.2.5

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/ScientificTypes.jl#43]
- [x] (**fix**) simplify the `autotype` logic, now when there are "few" values and the type is `<:Real`, the suggested type will be OrderedFactor (always) whereas before it could be Multiclass but that was inconsistent (PR #46)
- [x] allow `autotype` on AbstractArray (in particular vector), issue #47
- [x] Bump to O.2.5

**Comment by tlienart** [comment]
@ablaom I'm not a full admin of this repo unfortunately  so I cannot tag a new patch release

**Comment by tlienart** [comment]
@JuliaRegistrator register

Release note:

- [x] (**fix**) simplify the `autotype` logic, now when there are "few" values and the type is `<:Real`, the suggested type will be OrderedFactor (always) whereas before it could be Multiclass but that was inconsistent (PR #46)
- [x] allow `autotype` on AbstractArray (in particular vector), issue #47

**Comment by tlienart** [comment]
For some reason I don't  understand, I cannot seem to trigger Julia registrator on this repo... @DilumAluthge any idea (I had tried tagging a version a few weeks back with the same issue). 

It doesn't seem to be a rights problem afaik bc I'm also admin of this repo?

**Comment by tlienart** [comment]
@JuliaRegistrator register

Release note:

- [x] (**fix**) simplify the `autotype` logic, now when there are "few" values and the type is `<:Real`, the suggested type will be OrderedFactor (always) whereas before it could be Multiclass but that was inconsistent (PR #46)
- [x] allow `autotype` on AbstractArray (in particular vector), issue #47

**Comment by DilumAluthge** [comment]
Looks like Registrator is finally working on this repository?

**Comment by ablaom** [comment]
All good, thanks
